from pydantic import BaseModel


class TechStackItem(BaseModel):
    """A single item in the tech stack."""
    name: str
    purpose: str


class ModuleInfo(BaseModel):
    """A logical module/component within the repository."""
    name: str
    description: str
    key_files: list[str]


class DependencyInfo(BaseModel):
    """A single project dependency."""
    name: str
    version: str
    purpose: str


class SummaryResponse(BaseModel):
    """Structured summary of a repository generated by GPT-4o."""
    project_purpose: str
    tech_stack: dict[str, str]  # e.g. {"frontend": "React", "backend": "FastAPI"}
    folder_structure: str
    modules: list[ModuleInfo]
    dependencies: list[DependencyInfo]
